"""Pick data models."""

from __future__ import annotations

from datetime import datetime
from enum import Enum

from pydantic import BaseModel, Field


class Conviction(str, Enum):
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"


class Pick(BaseModel):
    """A stock pick generated by the strategy."""

    ticker: str
    conviction: Conviction
    direction: str = "long"  # "long" or "short"
    reasoning: str = ""
    entry_price: float | None = None
    strategy_version: int = 1
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    signals_used: int = 0  # how many signals informed this pick
    metadata: dict = Field(default_factory=dict)

    def summary(self) -> str:
        return f"{self.direction.upper()} {self.ticker} ({self.conviction.value}) — {self.reasoning[:100]}"
