"""CLI interface for Finn."""

from __future__ import annotations

import typer
from rich.console import Console
from rich.table import Table

from finn.config import get_settings

app = typer.Typer(
    name="finn",
    help="Finn: Self-evolving financial AI agent",
    no_args_is_help=True,
)
console = Console()


@app.command()
def run():
    """Execute the daily cycle: collect signals, generate picks, evaluate, evolve."""
    from finn.main import daily_run

    settings = get_settings()
    result = daily_run(settings)

    if result["picks"]:
        console.print(f"\n[bold]Summary: {len(result['picks'])} picks from {result['signals_collected']} signals[/bold]")
    else:
        console.print("\n[yellow]No picks generated. Check signal collection.[/yellow]")


@app.command()
def status():
    """Show current strategy and recent performance."""
    settings = get_settings()

    from finn.database import Database
    from finn.evolution.rollback import RollbackManager
    from finn.strategy.runner import StrategyRunner
    from pathlib import Path

    db = Database(settings.db_path)
    try:
        version = db.get_active_strategy_version()
        perf = db.get_strategy_performance(version)
        positions = db.get_open_positions()
        days = db.get_total_days_with_picks()

        console.rule("[bold blue]Finn Status")

        console.print(f"Active strategy: v{version}")
        console.print(f"Days running: {days}")
        console.print(f"Total picks: {perf.get('total_picks', 0)}")
        console.print(f"Win rate: {perf.get('win_rate', 0):.1%}")
        console.print(f"Avg return: {perf.get('avg_return') or 0:.2f}%")
        console.print(f"Crypto: {'enabled' if settings.enable_crypto else 'disabled'}")
        console.print(f"Trading: {'enabled (' + ('paper' if settings.alpaca_paper else 'LIVE') + ')' if settings.enable_trading else 'disabled'}")

        if positions:
            console.print(f"\nOpen positions ({len(positions)}):")
            table = Table()
            table.add_column("Ticker")
            table.add_column("Direction")
            table.add_column("Return %")
            table.add_column("Days Held")

            for pos in positions:
                table.add_row(
                    pos["ticker"],
                    pos["direction"],
                    f"{pos.get('return_pct', 0):+.1f}%",
                    str(pos.get("days_held", 0)),
                )
            console.print(table)

        # Show strategy description
        runner = StrategyRunner(settings.strategies_path)
        active_path = Path(__file__).parent / "strategy" / "active" / "strategy_v1.py"
        rollback = RollbackManager(db, settings.strategies_path, active_path)
        try:
            code = rollback.get_current_code()
            strategy = runner.load_strategy(code)
            console.print(f"\nStrategy description:\n{strategy.describe()}")
        except Exception:
            pass

        # Show recent memory
        memories = db.get_recent_memories("reflection", limit=1)
        if memories:
            console.print(f"\nLatest reflection:\n[dim]{memories[0]['content'][:300]}...[/dim]")

    finally:
        db.close()


@app.command()
def history():
    """Show strategy evolution timeline."""
    settings = get_settings()

    from finn.database import Database

    db = Database(settings.db_path)
    try:
        versions = db.get_all_strategy_versions()

        if not versions:
            console.print("[yellow]No strategy versions recorded yet. Run 'finn run' first.[/yellow]")
            return

        console.rule("[bold blue]Strategy Evolution History")

        table = Table()
        table.add_column("Version")
        table.add_column("Created")
        table.add_column("Parent")
        table.add_column("Active")
        table.add_column("Description")

        for v in versions:
            table.add_row(
                f"v{v['version']}",
                v["created_at"][:16],
                f"v{v['parent_version']}" if v.get("parent_version") else "-",
                "Yes" if v.get("is_active") else "",
                (v.get("description") or "")[:80],
            )
        console.print(table)

    finally:
        db.close()


@app.command()
def journal(days: int = typer.Option(7, help="Number of recent entries to show")):
    """Show recent journal entries."""
    settings = get_settings()
    journal_path = settings.journal_path

    files = sorted(journal_path.glob("*.md"), reverse=True)[:days]

    if not files:
        console.print("[yellow]No journal entries yet. Run 'finn run' first.[/yellow]")
        return

    for f in files:
        console.print(f.read_text())
        console.print()


@app.command()
def post(days: int = typer.Option(5, help="Number of recent posts to show")):
    """Show recent LinkedIn posts generated by Finn."""
    settings = get_settings()
    from finn.database import Database

    db = Database(settings.db_path)
    try:
        posts = db.get_recent_linkedin_posts(limit=days)
        if not posts:
            console.print("[yellow]No LinkedIn posts yet. Run 'finn run' with ANTHROPIC_API_KEY set.[/yellow]")
            return

        for p in posts:
            console.rule(f"[bold blue]{p['date']}")
            console.print(p["content"])
            console.print()
    finally:
        db.close()


@app.command()
def questions():
    """Show pending questions from Finn."""
    settings = get_settings()
    from finn.human_loop import HumanInTheLoop
    from finn.database import Database

    db = Database(settings.db_path)
    human_loop = HumanInTheLoop(db, settings.data_path)

    pending = human_loop.get_pending_questions()
    if not pending:
        console.print("[green]No pending questions. Finn's got it handled.[/green]")
        db.close()
        return

    console.rule("[bold blue]Finn's Questions")
    for q in pending:
        console.print(f"\n[bold]{q['id']}[/bold] [{q['priority']}]")
        console.print(f"  {q['question']}")
        if q.get("context"):
            console.print(f"  [dim]Context: {q['context']}[/dim]")
        console.print(f"  [dim]Asked: {q['asked_at'][:16]}[/dim]")

    console.print(f"\nAnswer with: [bold]finn answer <question_id> \"your answer\"[/bold]")
    db.close()


@app.command()
def answer(question_id: str, response: str):
    """Answer one of Finn's questions."""
    settings = get_settings()
    from finn.human_loop import HumanInTheLoop
    from finn.database import Database

    db = Database(settings.db_path)
    human_loop = HumanInTheLoop(db, settings.data_path)

    if human_loop.answer(question_id, response):
        console.print(f"[green]Answered {question_id}. Finn will use this in the next evolution cycle.[/green]")
    else:
        console.print(f"[red]Question {question_id} not found.[/red]")
    db.close()


@app.command()
def memory(count: int = typer.Option(5, help="Number of recent memories to show")):
    """Show Finn's recent memory reflections."""
    settings = get_settings()
    from finn.database import Database

    db = Database(settings.db_path)
    try:
        memories = db.get_recent_memories("reflection", limit=count)
        if not memories:
            console.print("[yellow]No memories yet. Finn needs a few days to start reflecting.[/yellow]")
            return

        console.rule("[bold blue]Finn's Memory")
        for m in memories:
            console.print(f"\n[bold]{m['date']}[/bold]")
            console.print(m["content"])
            console.print()
    finally:
        db.close()


@app.command()
def trades(days: int = typer.Option(30, help="Days of trade history to show")):
    """Show recent trade history."""
    settings = get_settings()
    from finn.database import Database

    db = Database(settings.db_path)
    try:
        recent = db.get_recent_trades(days)
        if not recent:
            console.print("[yellow]No trades yet. Enable trading with FINN_ENABLE_TRADING=true.[/yellow]")
            return

        console.rule("[bold blue]Trade History")
        table = Table()
        table.add_column("Time")
        table.add_column("Mode")
        table.add_column("Side")
        table.add_column("Ticker")
        table.add_column("Amount")
        table.add_column("Conviction")
        table.add_column("Status")

        for t in recent:
            table.add_row(
                t["timestamp"][:16],
                t.get("mode", "?"),
                t.get("side", "?").upper(),
                t["ticker"],
                f"${t.get('notional', 0):.2f}" if t.get("notional") else "?",
                t.get("conviction", "?"),
                t.get("status", "?"),
            )
        console.print(table)
    finally:
        db.close()


@app.command()
def schedule(
    interval_hours: int = typer.Option(24, help="Hours between runs"),
    run_at: str = typer.Option("09:30", help="Time to run daily (HH:MM)"),
):
    """Start the scheduler for automated daily runs."""
    import schedule as sched
    import time
    from finn.main import daily_run

    settings = get_settings()

    console.print(f"[bold]Scheduling Finn to run daily at {run_at}[/bold]")
    console.print("Press Ctrl+C to stop.\n")

    def job():
        try:
            daily_run(settings)
        except Exception as e:
            console.print(f"[red]Run failed: {e}[/red]")

    sched.every().day.at(run_at).do(job)

    # Also run immediately on first start
    console.print("[dim]Running initial cycle now...[/dim]\n")
    job()

    while True:
        sched.run_pending()
        time.sleep(60)


if __name__ == "__main__":
    app()
